#basic chatbot of 20 lines
print("welcome")
name = input("what is your name? ")
print(f"hello {name}, nice to meet you!")
print("What is your favorite hobby?")
hobby = input("My favorite hobby is ")
print(f"That's awesome! I also enjoy {hobby}.")
print("What is your favorite book?")
book = input("My favorite book is ")
print(f"{book} is a fantastic read!")
print("What is your favorite movie?")
movie = input("My favorite movie is ")
print(f"{movie} is a great film!")
print("What is your favorite color?")
color = input("My favorite color is ")
print(f"{color} is a beautiful color!")
print("What is your favorite food?")
food = input("My favorite food is ")
print(f"Yum! {food} sounds delicious!")
